name: CI/CD Pipeline

# Run this workflow when code is pushed to the 'main' branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java (if you're using Java)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # specify the version you're using

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Assuming you're using an artifact from the previous build step
      - name: Deploy to Server (Example using SCP or SSH)
        run: |
          scp -r ./target/* user@your-server:/path/to/deployment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Store SSH key in secrets
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
